print("Lab 1: Version Control")
print("Author: [Renz Bimmao]")
print("Student ID: TUPM-25-0799")
print("Lab 1: Version Control")
print("Author: Renz Bimmaol")
print("Student ID: TUPM-25-0799")
print("Class Section: [BSME-1C]")
